/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ApiBlogRouteImport } from './routes/api/blog'
import { Route as ApiActivityFeedRouteImport } from './routes/api/activity-feed'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogRoute = ApiBlogRouteImport.update({
  id: '/api/blog',
  path: '/api/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivityFeedRoute = ApiActivityFeedRouteImport.update({
  id: '/api/activity-feed',
  path: '/api/activity-feed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/activity-feed': typeof ApiActivityFeedRoute
  '/api/blog': typeof ApiBlogRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/activity-feed': typeof ApiActivityFeedRoute
  '/api/blog': typeof ApiBlogRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/activity-feed': typeof ApiActivityFeedRoute
  '/api/blog': typeof ApiBlogRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/activity-feed' | '/api/blog' | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/activity-feed' | '/api/blog' | '/blog'
  id: '__root__' | '/' | '/api/activity-feed' | '/api/blog' | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiActivityFeedRoute: typeof ApiActivityFeedRoute
  ApiBlogRoute: typeof ApiBlogRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog': {
      id: '/api/blog'
      path: '/api/blog'
      fullPath: '/api/blog'
      preLoaderRoute: typeof ApiBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activity-feed': {
      id: '/api/activity-feed'
      path: '/api/activity-feed'
      fullPath: '/api/activity-feed'
      preLoaderRoute: typeof ApiActivityFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiActivityFeedRoute: ApiActivityFeedRoute,
  ApiBlogRoute: ApiBlogRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
